name: Rebase on upstream master
on:
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rebase on upstream
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          git pull --unshallow

          git remote add upstream https://github.com/PrismLauncher/meta-launcher.git
          git pull --rebase upstream master

          git push --force origin master
